{% set name = "gobject-introspection" %}
{% set version = "1.68.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: d229242481a201b84a0c66716de1752bca41db4133672cfcfb37c93eb6e54a27
  patches:
    - cross-compile.patch
    - test-fix.patch  # [linux]
    # https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/265
    - pkg-config.patch

build:
  number: 1
  skip: true  # [py<35]

requirements:
  build:
    - python {{ python }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ posix }}bison
    - {{ posix }}flex
    - meson
    - ninja
    - {{ posix }}patch
    - {{ native }}pkg-config
    - {{ compiler('c') }}
    - glib     # [build_platform != target_platform]
    - cairo    # [build_platform != target_platform]
    - libffi   # [build_platform != target_platform]
  host:
    - cairo
    - glib
    - libffi
    - python
  run:
    - libffi
    - python

test:
  requires:
    - pkg-config
  commands:
    - g-ir-scanner --help  # [not win]
    - python "%PREFIX%\\Library\\bin\\g-ir-scanner" --help  # [win]
    - g-ir-compiler --help

    # check that g-ir-scanner can be found through pkg-config (used by downstream builds)
    - test -f `pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`  # [unix]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`) do if not exist "%%a" exit 1  # [win]
  downstreams:
    - pygobject

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - scopatz
    - tschoonj
